### PR TITLE
update azure free tier for virtual machines

### PR DESCRIPTION
**Pull request by anakimluke**
Sources:
https://azure.microsoft.com/en-us/free/#all-free-services
https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/create-free-services

### CODE REVIEW

**Comment by steom** [comment]
Absolutely not always free. 
Only 12 months.

Screenshot_20230115_124504

**Comment by karentamrazyan** [comment]
thanks @steom 
Corrected it with https://github.com/cloudcommunity/Cloud-Free-Tier-Comparison/commit/0c9afb43c7e4a04734b229e9c5c665f3388c2a9e

**Comment by anakimluke** [comment]
oh, my bad. I though it was part of the always free offer. it's doesn't help that the when you click the "55+ other services free always" button the first thing you see is the example of the 750 hours of Virtual Machine.

**Comment by karentamrazyan** [comment]
no worries at all, @anakimluke ! Thanks for the initiative anyways 🙏

**Pull request merged**
